export const SET_LOCATION = 'SET_LOCATION'
export const CLEAR_LOCATION = 'CLEAR_LOCATION'
export const ACQUIRE_LOCATION = 'ACQUIRE_LOCATION'

/**
 * API ActionTypes
 */
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'

export const CREATE_WISSLE_SUCCESS = 'CREATE_WISSLE_SUCCESS'

export const CREATE_TAG_SUCCESS = 'CREATE_TAG_SUCCESS'
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'
