export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL'
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR'
