export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const CREATE_WISSLE_SUCCESS = 'CREATE_WISSLE_SUCCESS';
